/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Base = "standard"[];
export type BaseColor = (
  | (
      | "apricot"
      | "coast"
      | "topaz"
      | "lavender"
      | "sky"
      | "salmon"
      | "canary"
      | "calm"
      | "azure"
      | "seashell"
      | "mellow"
      | "black"
      | "white"
    )
  | string
)[];
export type Earrings = ("hoop" | "stud")[];
export type EarringColor = (
  | (
      | "apricot"
      | "coast"
      | "topaz"
      | "lavender"
      | "sky"
      | "salmon"
      | "canary"
      | "calm"
      | "azure"
      | "seashell"
      | "mellow"
      | "black"
      | "white"
    )
  | string
)[];
export type EarringsProbability = number;
export type Eyebrows = ("down" | "eyelashesDown" | "eyelashesUp" | "up")[];
export type EyebrowColor = (
  | (
      | "apricot"
      | "coast"
      | "topaz"
      | "lavender"
      | "sky"
      | "salmon"
      | "canary"
      | "calm"
      | "azure"
      | "seashell"
      | "mellow"
      | "black"
      | "white"
    )
  | string
)[];
export type Ears = "attached"[];
export type Eyes = ("eyes" | "eyesShadow" | "round" | "smiling")[];
export type EyeColor = (
  | (
      | "apricot"
      | "coast"
      | "topaz"
      | "lavender"
      | "sky"
      | "salmon"
      | "canary"
      | "calm"
      | "azure"
      | "seashell"
      | "mellow"
      | "black"
      | "white"
    )
  | string
)[];
export type FacialHair = ("beard" | "scruff")[];
export type FacialHairColor = (
  | (
      | "apricot"
      | "coast"
      | "topaz"
      | "lavender"
      | "sky"
      | "salmon"
      | "canary"
      | "calm"
      | "azure"
      | "seashell"
      | "mellow"
      | "black"
      | "white"
    )
  | string
)[];
export type FacialHairProbability = number;
export type Glasses = ("round" | "square")[];
export type GlassesColor = (
  | (
      | "apricot"
      | "coast"
      | "topaz"
      | "lavender"
      | "sky"
      | "salmon"
      | "canary"
      | "calm"
      | "azure"
      | "seashell"
      | "mellow"
      | "black"
      | "white"
    )
  | string
)[];
export type GlassesProbability = number;
export type Mouth = ("frown" | "laughing" | "nervous" | "pucker" | "sad" | "smile" | "smirk" | "surprised")[];
export type Nose = ("curve" | "pointed" | "round")[];
export type Shirt = ("collared" | "crew" | "open")[];
export type ShirtColor = (
  | (
      | "apricot"
      | "coast"
      | "topaz"
      | "lavender"
      | "sky"
      | "salmon"
      | "canary"
      | "calm"
      | "azure"
      | "seashell"
      | "mellow"
      | "black"
      | "white"
    )
  | string
)[];
export type Hair = ("dannyPhantom" | "dougFunny" | "fonze" | "full" | "mrClean" | "mrT" | "pixie" | "turban")[];
export type HairColor = (
  | (
      | "apricot"
      | "coast"
      | "topaz"
      | "lavender"
      | "sky"
      | "salmon"
      | "canary"
      | "calm"
      | "azure"
      | "seashell"
      | "mellow"
      | "black"
      | "white"
    )
  | string
)[];
export type HairProbability = number;

export interface Options {
  base?: Base;
  baseColor?: BaseColor;
  earrings?: Earrings;
  earringColor?: EarringColor;
  earringsProbability?: EarringsProbability;
  eyebrows?: Eyebrows;
  eyebrowColor?: EyebrowColor;
  ears?: Ears;
  eyes?: Eyes;
  eyeColor?: EyeColor;
  facialHair?: FacialHair;
  facialHairColor?: FacialHairColor;
  facialHairProbability?: FacialHairProbability;
  glasses?: Glasses;
  glassesColor?: GlassesColor;
  glassesProbability?: GlassesProbability;
  mouth?: Mouth;
  nose?: Nose;
  shirt?: Shirt;
  shirtColor?: ShirtColor;
  hair?: Hair;
  hairColor?: HairColor;
  hairProbability?: HairProbability;
  [k: string]: unknown;
}
