/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Options = {
  seed?: Seed;
  radius?: Radius;
  dataUri?: DataURI;
  width?: Width;
  height?: Height;
  margin?: Margin;
  backgroundColor?: BackgroundColor;
  [k: string]: unknown;
} & {
  base?: Base;
  baseColor?: BaseColor;
  earrings?: Earrings;
  earringColor?: EarringColor;
  earringsProbability?: EarringsProbability;
  eyebrows?: Eyebrows;
  eyebrowColor?: EyebrowColor;
  ears?: Ears;
  eyes?: Eyes;
  eyeColor?: EyeColor;
  facialHair?: FacialHair;
  facialHairColor?: FacialHairColor;
  facialHairProbability?: FacialHairProbability;
  glasses?: Glasses;
  glassesColor?: GlassesColor;
  glassesProbability?: GlassesProbability;
  mouth?: Mouth;
  nose?: Nose;
  shirt?: Shirt;
  shirtColor?: ShirtColor;
  hair?: Hair;
  hairColor?: HairColor;
  hairProbability?: HairProbability;
  [k: string]: unknown;
};
export type Seed = string;
export type Radius = number;
export type DataURI = boolean;
export type Width = number;
export type Height = number;
export type Margin = number;
export type BackgroundColor = string[];
export type Base = "standard"[];
export type BaseColor = (
  | (
      | "apricot"
      | "coast"
      | "topaz"
      | "lavender"
      | "sky"
      | "salmon"
      | "canary"
      | "calm"
      | "azure"
      | "seashell"
      | "mellow"
      | "black"
      | "white"
    )
  | string
)[];
export type Earrings = ("hoop" | "stud")[];
export type EarringColor = (
  | (
      | "apricot"
      | "coast"
      | "topaz"
      | "lavender"
      | "sky"
      | "salmon"
      | "canary"
      | "calm"
      | "azure"
      | "seashell"
      | "mellow"
      | "black"
      | "white"
    )
  | string
)[];
export type EarringsProbability = number;
export type Eyebrows = ("eyelashesDown" | "eyelashesUp" | "down" | "up")[];
export type EyebrowColor = (
  | (
      | "apricot"
      | "coast"
      | "topaz"
      | "lavender"
      | "sky"
      | "salmon"
      | "canary"
      | "calm"
      | "azure"
      | "seashell"
      | "mellow"
      | "black"
      | "white"
    )
  | string
)[];
export type Ears = "attached"[];
export type Eyes = ("smiling" | "eyes" | "eyesShadow" | "round")[];
export type EyeColor = (
  | (
      | "apricot"
      | "coast"
      | "topaz"
      | "lavender"
      | "sky"
      | "salmon"
      | "canary"
      | "calm"
      | "azure"
      | "seashell"
      | "mellow"
      | "black"
      | "white"
    )
  | string
)[];
export type FacialHair = ("beard" | "scruff")[];
export type FacialHairColor = (
  | (
      | "apricot"
      | "coast"
      | "topaz"
      | "lavender"
      | "sky"
      | "salmon"
      | "canary"
      | "calm"
      | "azure"
      | "seashell"
      | "mellow"
      | "black"
      | "white"
    )
  | string
)[];
export type FacialHairProbability = number;
export type Glasses = ("round" | "square")[];
export type GlassesColor = (
  | (
      | "apricot"
      | "coast"
      | "topaz"
      | "lavender"
      | "sky"
      | "salmon"
      | "canary"
      | "calm"
      | "azure"
      | "seashell"
      | "mellow"
      | "black"
      | "white"
    )
  | string
)[];
export type GlassesProbability = number;
export type Mouth = ("laughing" | "nervous" | "pucker" | "sad" | "smile" | "smirk" | "surprised" | "frown")[];
export type Nose = ("curve" | "pointed" | "round")[];
export type Shirt = ("collared" | "crew" | "open")[];
export type ShirtColor = (
  | (
      | "apricot"
      | "coast"
      | "topaz"
      | "lavender"
      | "sky"
      | "salmon"
      | "canary"
      | "calm"
      | "azure"
      | "seashell"
      | "mellow"
      | "black"
      | "white"
    )
  | string
)[];
export type Hair = ("pixie" | "dannyPhantom" | "dougFunny" | "fonze" | "full" | "mrClean" | "mrT" | "turban")[];
export type HairColor = (
  | (
      | "apricot"
      | "coast"
      | "topaz"
      | "lavender"
      | "sky"
      | "salmon"
      | "canary"
      | "calm"
      | "azure"
      | "seashell"
      | "mellow"
      | "black"
      | "white"
    )
  | string
)[];
export type HairProbability = number;
