cdn:
  blocked:
    referrer: []

  redirect:
    # Redirect to primary domain
    https://{{process.env.BUNNYCDN_HOSTNAME}}{{path}}:
      - https://{{process.env.BUNNYCDN_PULL_ZONE_NAME}}.b-cdn.net/*
      - https://{{process.env.BUNNYCDN_ORIGIN}}/*
      - https://dicebear.com/*
      - https://www.dicebear.com/*

  header:
    remove: []

  cors:
    - https://{{process.env.BUNNYCDN_HOSTNAME}}/stats.json
    - https://{{process.env.BUNNYCDN_HOSTNAME}}/api/*
    - https://{{process.env.BUNNYCDN_HOSTNAME}}/*/api/*
    - https://{{process.env.BUNNYCDN_HOSTNAME}}/v2/*
    - https://{{process.env.BUNNYCDN_HOSTNAME}}/*/v2/*

  cache:
    server:
      1y:
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/api/*
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/*/api/*
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/v2/*
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/*/v2/*

    client:
      1h:
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/docs*
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/styles*
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/integrations*
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/legal*
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/faq*
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/sitemap.xml
      30d:
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/*.js
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/*.css
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/*.png
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/*.jpg
        - https://{{process.env.BUNNYCDN_HOSTNAME}}/*.svg

  origin:
    https://{{process.env.BUNNYCDN_ORIGIN}}:
      - https://{{process.env.BUNNYCDN_HOSTNAME}}/api/*
      - https://{{process.env.BUNNYCDN_HOSTNAME}}/*/api/*
      - https://{{process.env.BUNNYCDN_HOSTNAME}}/v2/*
      - https://{{process.env.BUNNYCDN_HOSTNAME}}/*/v2/*
      - https://{{process.env.BUNNYCDN_HOSTNAME}}/stats.json
